force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <displayFormat>REF - {00000}</displayFormat>
        <label>Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referee__c/fields/Picture_Path__c.field-meta.xml
<CustomField>
    <fullName>Picture_Path__c</fullName>
    <description>path for pic</description>
    <label>Picture Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AttachmentController.cls
public with sharing class AttachmentController {
    
   @AuraEnabled
    public static void updatePicturePath(String recId){
        //In Lightning Experience, Attachments are stored in ContentDocuments
        ContentDocumentLink docLink;
         docLink = [ SELECT ContentDocumentId
                               FROM ContentDocumentLink
                               WHERE LinkedEntityId = :recId order by Id desc Limit 1];
        //ContentVersion Id uniquely identifies the attachment
		ContentVersion ver = [SELECT Id FROM ContentVersion Where ContentDocumentId = :docLink.ContentDocumentId];
        //Update the Picture_Path field with the url of the image
        Referee__c ref = [SELECT Id FROM Referee__c WHERE Id = :recId];
        ref.Picture_Path__c = '/sfc/servlet.shepherd/version/download/'+ ver.Id;
        upsert ref;
    }


}