force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <displayFormat>REF - {00000}</displayFormat>
        <label>Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RefereesController.cls
public with sharing class RefereesController {
    @AuraEnabled
    public static List<Referee__c> getReferees(){
        return [SELECT Id, First_Name__c,Last_Name__c, Email__c, CreatedDate, IsDeleted FROM Referee__c LIMIT 5];

    }
    @AuraEnabled
    public static Referee__c saveReferee(Referee__c referee){
        //perfor logic to check intege
        upsert referee;
        return referee;
        
    }
}