force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <displayFormat>REF - {00000}</displayFormat>
        <label>Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Referee__c/Session_Referee__c.object-meta.xml
<CustomObject>
    <description>The Session Referee object is used to model the m-m relationship between Session and Referee: A Session can have one or many Referees , and a Ref can have one or many sessions.</description>
    <label>Session Referee</label>
    <nameField>
        <displayFormat>SERE-{00000}</displayFormat>
        <label>Session Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Referees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Referee__c/fields/Referee__c.field-meta.xml
<CustomField>
    <fullName>Referee__c</fullName>
    <label>Referee</label>
    <referenceTo>Referee__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Session_Referees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Referee__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Referees</relationshipLabel>
    <relationshipName>Session_Referees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RefereeGateway.cls
/**
class RefereeGateway

provides finder methods for accessing data in the Referee object
*/

public without sharing class RefereeGateway {
   /**
   Return a subject of Id's where there are any records in use

   Arguments:  Set<Id> refIds - Set of Referee Id's to examine

   Returns: Se<Id> - Set of Referee Id's that are 'in use' by Session Ids
   */
   public static set<Id> findRefereeIdsInUse(Set<Id> refIds)
   {
       //to add all id being use
       Set<Id> inUseIds = New Set<Id>(); 
       //session Id to be track to check if the Referesee has no session in place
        Set<Id> seIds = New Set<Id>();
     

    Session_Referee__c[] refses = [SELECT Referee__c, Session__c, Id, Name 
                               FROM Session_Referee__c];
   
   

    for( Session_Referee__c refse : refses)
    {
        seIds.add(refse.Session__c);
        if(seIds.size()> 0 ){
            inUseIds.add(refse.Id);
        }
    }

       
      
   }
   
}