force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <displayFormat>REF - {00000}</displayFormat>
        <label>Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Referee__c/Session_Referee__c.object-meta.xml
<CustomObject>
    <description>The Session Referee object is used to model the m-m relationship between Session and Referee: A Session can have one or many Referees , and a Ref can have one or many sessions.</description>
    <label>Session Referee</label>
    <nameField>
        <displayFormat>SERE-{00000}</displayFormat>
        <label>Session Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Referees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Referee__c/fields/Referee__c.field-meta.xml
<CustomField>
    <fullName>Referee__c</fullName>
    <label>Referee</label>
    <referenceTo>Referee__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Session_Referees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Referee__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Referees</relationshipLabel>
    <relationshipName>Session_Referees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestRefereeDataFactory.cls
@isTest
public class TestRefereeDataFactory {

    public static List<Referee__c> createRefereeWithSessions(Integer num_refs, Integer num_sessions){
        List<Referee__c> refs = New List<Referee__c>();

        for(Integer i = 0; i< num_refs; i++){
            Referee__c r = New Referee__c(First_Name__c = ' Test Ref');
            refs.add(r);

        }
        insert refs;
        List<Session_Referee__c> session_refs = New List<Session_Referee__c>();

        List<Session__c> sessions = New List<Session__c>();
        for(Integer j= 0; j<num_refs; j++){
            Referee__c ref = refs[j];
            // for each Ref just inserted, add Sessions
            for(Integer k = 0; k< num_sessions; k++){
                sessions.add(New Session__c(Name = ' Test Session'+k ));
                Session_Referee__c sr = New Session_Referee__c();
                sr.Referee__c = refs[j].id;
                sr.Session__c = sessions[k].id;

            }
            insert sessions;

        }
        return refs;
        

    }
    
   
    }