force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <displayFormat>REF - {00000}</displayFormat>
        <label>Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Referee__c/Session_Referee__c.object-meta.xml
<CustomObject>
    <description>The Session Referee object is used to model the m-m relationship between Session and Referee: A Session can have one or many Referees , and a Ref can have one or many sessions.</description>
    <label>Session Referee</label>
    <nameField>
        <displayFormat>SERE-{00000}</displayFormat>
        <label>Session Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Referees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Referee__c/fields/Referee__c.field-meta.xml
<CustomField>
    <fullName>Referee__c</fullName>
    <label>Referee</label>
    <referenceTo>Referee__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Session_Referees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Referee__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Referees</relationshipLabel>
    <relationshipName>Session_Referees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DataSetup.cls
public class DataSetup {

     public static void createRefereeWithSessions(Integer num_refs, Integer num_sessions){
        
        
    List<Referee__c> refs = New List<Referee__c>();
    List<Session__c> sessions = New List<Session__c>();
    List<Session_Referee__c> session_refs = New List<Session_Referee__c>();
        //refs
			for(Integer i = 0; i< 10; i++){
            Referee__c r = New Referee__c(First_Name__c = ' Test Ref' + i );
            refs.add(r);
        }
        insert refs;
       //session
        for(Integer k = 0; k<10; k++){
            sessions.add(New Session__c(Name = ' Test Session'+k ));

        }
        insert sessions;
	
        //A ref can have 1o session 
        //A Session can have 10 Refs convering the event:wq
        

    }

}