force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <displayFormat>REF - {00000}</displayFormat>
        <label>Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SessionRefereeCreate.cls
public class SessionRefereeCreate {
    /*
     * Enter Name to Indentify session and referee name along number of accounts to created
     * 
     */
    public static void Create(String Name, Integer numberOfRefs){
        //ref creation
        List<Referee__c> refs = New List<Referee__c>();
        List<Session__c> sessList = New List<Session__c>();
        for (Integer i=0; i< numberOfRefs; i++){
            Referee__c ref = New Referee__c();
    		ref.First_Name__c = Name + i;
    		ref.Last_Name__c  = 'Alvararez' + i;
    		ref.Email__c      = 'pa@email.com' + i;
   			ref.Bio__c  	= 'Back from the dead' + i;
            Session__c sess = New Session__c();
            sess.Name = Name + 'Sunny Sunday'+ i ;
            
            //sess
            sessList.add(sess);
            //refs
    		refs.add(ref); 
        }
       
        /**
         * 
         * TODO 
         * Relate Sessiona and referee when I created them. 
         * Just to test my skills 
         */
        
       
        
        
    }
      
}