force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <displayFormat>REF - {00000}</displayFormat>
        <label>Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <label>Session Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session_Referee__c/Session_Referee__c.object-meta.xml
<CustomObject>
    <description>The Session Referee object is used to model the m-m relationship between Session and Referee: A Session can have one or many Referees , and a Ref can have one or many sessions.</description>
    <label>Session Referee</label>
    <nameField>
        <displayFormat>SERE-{00000}</displayFormat>
        <label>Session Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Referees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Referee__c/fields/Referee__c.field-meta.xml
<CustomField>
    <fullName>Referee__c</fullName>
    <label>Referee</label>
    <referenceTo>Referee__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Session_Referees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Referee__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Referees</relationshipLabel>
    <relationshipName>Session_Referees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestRejectBooking.cls
@isTest
public class TestRejectBooking {
    
    @isTest static void TestingSingleBooking(){
        Datetime now = System.now();
        Referee__c referee = New Referee__c(First_Name__c='John',
                                           Last_Name__c='smith');
        insert referee;
        
        Session__c session = New Session__c(Name='Some session', 
                                           Session_Date__c=now);
        insert session;
        Session_Referee__c assigment = New Session_Referee__c(Session__c = session.Id,
                                                             Referee__c = referee.Id);
        Database.SaveResult result = Database.insert(assigment, false);
        System.assert(result.isSuccess());
    }
    static testmethod void TestDoubleBooking() {
    Datetime now = System.now();
    Referee__c referee = new Referee__c(First_Name__c='John', Last_Name__c='Smith');
    insert referee;
    Session__c session1 = new Session__c(Name='Session 1', Session_Date__c=now);
    insert session1;
    Session__c session2 = new Session__c(Name='Session 2', Session_Date__c=now);
    insert session2;
    Session_Referee__c assignment1 =
    new Session_Referee__c(Session__c=session1.Id, Referee__c=referee.Id);
    insert assignment1;
    Session_Referee__c assignment2 =
    new Session_Referee__c(Session__c=session2.Id, Referee__c=referee.Id);
    Database.SaveResult result = Database.insert(assignment2, false);
    System.assert(!result.isSuccess());
}


}