force-app/main/default/objects/Audit__c/Audit__c.object-meta.xml
<CustomObject>
    <label>Audit</label>
    <nameField>
        <displayFormat>AUDIT-{0000}</displayFormat>
        <label>Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Detail Description of what happened</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Referee__c/Referee__c.object-meta.xml
<CustomObject>
    <label>Referee</label>
    <nameField>
        <displayFormat>REF - {00000}</displayFormat>
        <label>Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Referee__c/Session_Referee__c.object-meta.xml
<CustomObject>
    <description>The Session Referee object is used to model the m-m relationship between Session and Referee: A Session can have one or many Referees , and a Ref can have one or many sessions.</description>
    <label>Session Referee</label>
    <nameField>
        <displayFormat>SERE-{00000}</displayFormat>
        <label>Session Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Referees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Referee__c/fields/Referee__c.field-meta.xml
<CustomField>
    <fullName>Referee__c</fullName>
    <label>Referee</label>
    <referenceTo>Referee__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Session_Referees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Referee__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Referees</relationshipLabel>
    <relationshipName>Session_Referees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestSessionDeletetion.cls
@isTest
private class TestSessionDeletetion {
   @isTest static void TestDeleteRefereeWithOneSession(){
       //Test Data Setup
       //Created a Referee and and a Session , and add the session id and ref id
       Referee__c ref = New Referee__c(First_Name__c = 'Test ref');
       insert ref;
       Session__c session = New Session__c(Name = ' Test session');
       insert session;
       Session_Referee__c  session_ref = New Session_Referee__c(Session__c = session.Id, Referee__c=ref.Id);
       insert session_ref;

       Test.startTest();

       Database.DeleteResult dr = Database.delete(ref, false);

       Test.stopTest();
       
       System.assert(!dr.isSuccess());
       System.assert(dr.getErrors().size()> 0);
       System.assertEquals('You cannot delete refereee with session version2.'+ ref.Id, dr.getErrors()[0].getMessage());

       
   }

   @isTest static void TestDeleteRefereeWithoutSessions() {
       Referee__c ref = New Referee__c(First_Name__c = 'Test wihout session');
       insert ref;

       Audit__c audit = New Audit__c(Description__c = 'Test audit');

       Test.startTest();
       Database.DeleteResult dr = Database.delete(ref);
       Database.SaveResult sr = Database.insert(audit);
       Test.stopTest();

       System.assert(dr.isSuccess());
       System.assert(sr.isSuccess());

   }
}