force-app/main/default/objects/Contact/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to user</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/CoVisit.recordType-meta.xml
<RecordType>
    <fullName>CoVisit</fullName>
    <active>true</active>
    <description>Company Visits</description>
    <label>CoVisit</label>
</RecordType>

force-app/main/default/objects/Event_Attendee_Record__c/Event_Attendee_Record__c.object-meta.xml
<CustomObject>
    <description>Event Attendee Record(Relationship)</description>
    <label>Event Attendee Record</label>
    <nameField>
        <displayFormat>EAR-{00000}</displayFormat>
        <label>Event Attendee Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendee Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee_Record__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Attendee Records</relationshipLabel>
    <relationshipName>Event_Attendee_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Attendee_Record__c/fields/Visit_Detail__c.field-meta.xml
<CustomField>
    <fullName>Visit_Detail__c</fullName>
    <description>Relate Visit Detail to transverse all Visit details on EAR for Reporting</description>
    <label>Visit Detail</label>
    <referenceTo>Visit_Detail__c</referenceTo>
    <relationshipLabel>Event Attendee Records</relationshipLabel>
    <relationshipName>Event_Attendee_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee_Record__c/fields/VisitDetailContact__c.field-meta.xml
<CustomField>
    <fullName>VisitDetailContact__c</fullName>
    <description>This field is a combination of Visit Detail and Contact id, to prevent duplicate records from being inserted into this object</description>
    <label>VisitDetailContact</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Detail__c/Visit_Detail__c.object-meta.xml
<CustomObject>
    <label>Visit Detail</label>
    <nameField>
        <displayFormat>Visit-{00000}</displayFormat>
        <label>Visit Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Detail__c/fields/Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Segmentation__c</fullName>
    <description>How big is the opportunity</description>
    <label>Segmentation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High Grow</fullName>
            </value>
            <value>
                <fullName>Developing</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VisitsHelper.cls
public without sharing class VisitsHelper {
    
      
      public static final String Segmentation='Visit_Detail__r.Segmentation__c';
      public static final String Target_Focus= 'Visit_Detail__r.Target_Focus__c';
      public static final String Event_BR = 'whatid';
      private static final String EVENT_TYPE='CompanyVisits';
      private static final List<String> Event_Fields = New List<String>{'id','Subject', 'Description', ' whatid', 'createdbyid', 'startDateTime', '	Account_Discussed__c'};
      private static final List<String> Account_Fields = New List<String>{'id', 'Name','BillingCity', 'BillingState'};
      private static final LIst<String> Contact_Fields = New LIst<String>{'Id','Name', 'User__c'};
      private static final List<String> Visit_Detail_Fields = New List<String>{'Segmentation__c', 'Focus__c'};

      private VisitsHelper() {//Rules
      }

      public static List<Contact> getContactbyUserId(set<Id> userIdSet){
        Boolean userchek;
        userchek = True;
        List<Contact> returnList = New LIst<Contact>();
        if(userchek && null != userIdSet){
          returnList = [SELECT Id, Name, User__c FROM Contact WHERE User__c IN: userIdSet];
          
        }
        else {
          throw new AuraHandledException('Dont Have Permission to view Detail');
        }
        return returnList;

      }

/*
  public static List<Event> getEventsByEventRel(List<EventRelation> eventRelList, Date startDate, Date endDate, String segmentation, string orderBy,set<id> userIdSet){
  set<Id> eventIdSet = new Set<Id>();
  for(EventRelation  thisEvent : eventRelList){
    eventIdSet.add(thisEvent.eventId);
  }
  return getEventsByTimeFrame(eventIdSet, startDate, endDate, segmentation, orderBy, userIdSet);
}
*/

/*
public static List<CoVisit> buildVisitEvent (set<id> userIdSet, Date startDate, Date endDate, String segment, string sortOrder){
  List<Contact> contactList = VisitsHelper.getContactbyUserId(userIdSet);
  List<Id> visitIds = new LIst<Id>();
  for(Event_Attendee_Record__c ear : [SELECT Id, 	Visit_Detail__c,  VisitDetailContact__c, Contact__c FROM Event_Attendee_Record__c WHERE Contact__c IN: contactList]){
    visitIds.add(ear.Visit_Detail__c);
  }
  system.System.debug('VisitDetail Size ' + visitIds.Size());
  userchek = True;
  Set<Id> AssociateEventIds = New set<Id>(New Map<Id,Event>([SELECT Id, Is_Primary__c, Visit_Detail__c FROM Event WHERE Is_Primary__c = True AND Visit_Detail__c IN: visitIds]).keySet());
  
}
  **/    

}