force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Referee__c/Session_Referee__c.object-meta.xml
<CustomObject>
    <description>The Session Referee object is used to model the m-m relationship between Session and Referee: A Session can have one or many Referees , and a Ref can have one or many sessions.</description>
    <label>Session Referee</label>
    <nameField>
        <displayFormat>SERE-{00000}</displayFormat>
        <label>Session Referee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Referees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Referee__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Referees</relationshipLabel>
    <relationshipName>Session_Referees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SessionRefereeGateway.cls
/**
class SessionReferee

provides finder methods for accessing data in the in the Sesion Referee object
*/

public with sharing class SessionRefereeGateway {
     /**
   Return a subject of Id's where there are any records in use

   Arguments:  Set<Id> refIds - Set of Referee Id's to examine

   Returns: Se<Id> - Set of Referee Id's that are 'in use' by Session Ids
   */
   public static set<Id> findRefereeIdsInUse(Set<Id> refIds)
   {
       //to add all id being use
       Set<Id> inUseIds = New Set<Id>(); 
       //session Id to be track to check if the Referesee has no session in place
    
     for (Session_Referee__c[] refs : [Select p.Id, Session__c From Session_Referee__c p where p.Id in : refIds])
		{	
			for (Session_Referee__c ref : refs)
			{
				if (ref.Session__c<> null)
				{
					inUseIds.add(ref.Id);
				}
			}
		}

      return inUseIds;
   }
}