force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>This object will track expenses</description>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Total amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client name</description>
    <inlineHelpText>Enter client name not if same is contact</inlineHelpText>
    <label>Client</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Date_of_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Purchase__c</fullName>
    <description>Date of the transaction</description>
    <label>Date of Purchase</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Reimbursed__c.field-meta.xml
<CustomField>
    <fullName>Reimbursed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Was the money reinburse than run logic</description>
    <inlineHelpText>Was he offered a discount</inlineHelpText>
    <label>Reimbursed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ExpensesController.cls
public with sharing class ExpensesController {
    // STERN LECTURE ABOUT WHAT'S MISSING HERE COMING SOON
    @AuraEnabled
    public static List<Expense__c> getExpenses() {
        
        // Check to make sure all fields are accessible to this user
        
        
        // OK, they're cool, let 'em through
        return [SELECT Id, Name, Amount__c, Client__c, Date_Of_Purchase__c, 
                       Reimbursed__c, CreatedDate 
                FROM Expense__c];
    }
    @AuraEnabled
    public static Expense__c saveExpense(Expense__c expense) {
        // Perform isUpdateable() checking first, then
        upsert expense;
        return expense;
    }
}